[tool.poetry]
name = "jsbot"
version = "0.1.0"
description = "Bot Discord com Nextcord e Wavelink"
authors = ["iamkevyn <seu@email.com>"]
readme = "README.md" # Opcional, se você tiver um README

[tool.poetry.dependencies]
python = "^3.10" # Usar a versão Python do Railway (geralmente 3.10 ou 3.11)
nextcord = "==2.6.0"
wavelink = "==2.6.4"
PyNaCl = "==1.5.0"
python-dotenv = "==1.0.1"
flask = "==3.0.0" # Fixar versão do Flask também
setuptools = ">=65.5.0"
psutil = "==5.9.8"
aiohttp = "==3.8.5" # Versão compatível
yarl = "==1.8.2" # Versão compatível
multidict = "==6.0.4" # Dependência do aiohttp
frozenlist = "==1.3.3" # Dependência do aiohttp
spotipy = "==2.23.0"
yt-dlp = "==2023.11.14" # Versão estável

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
